In [27]:
import pandas as pd

In [28]:
data = pd.read_csv('kxr_sq_bu01.txt', sep='|')

In [29]:
data.columns

Index(['ID', 'SIDE', 'readprj', 'VERSION', 'V01BARCDBU', 'V01XROSFM',
       'V01XRSCFM', 'V01XRCYFM', 'V01XRJSM', 'V01XRCHM', 'V01XROSTM',
       'V01XRSCTM', 'V01XRCYTM', 'V01XRATTM', 'V01XRKL', 'V01XROSFL',
       'V01XRSCFL', 'V01XRCYFL', 'V01XRJSL', 'V01XRCHL', 'V01XROSTL',
       'V01XRSCTL', 'V01XRCYTL', 'V01XRATTL'],
      dtype='object')

In [30]:
data

,ID,SIDE,readprj,VERSION,V01BARCDBU,V01XROSFM,V01XRSCFM,V01XRCYFM,V01XRJSM,V01XRCHM,...,V01XRKL,V01XROSFL,V01XRSCFL,V01XRCYFL,V01XRJSL,V01XRCHL,V01XROSTL,V01XRSCTL,V01XRCYTL,V01XRATTL
0,9000099,1,15,1.8,016601653203,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,9000099,2,15,1.8,016601653203,0.0,0.0,0.0,0.0,0.0,...,4.0,2.0,2.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0
2,9000296,1,15,1.8,016601140204,0.0,0.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9000296,2,15,1.8,016601140204,0.0,1.0,0.0,2.0,0.0,...,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,9000622,1,15,1.8,016601597803,NaN,NaN,NaN,0.0,NaN,...,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8478,9999862,2,15,1.8,016601595304,0.0,0.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8479,9999865,1,15,1.8,016601436003,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
8480,9999865,2,15,1.8,016601436003,NaN,NaN,NaN,0.0,NaN,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
8481,9999878,1,15,1.8,016601317504,0.0,1.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8482,9999878,2,15,1.8,016601317504,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
data['V01XRKL'].unique()

array([ 2.,  4.,  3.,  1.,  0., nan])

In [26]:
data = pd.read_csv('downloads/enrollee01.txt', sep='\t')

/tmp/ipykernel_1549/535502798.py:1: DtypeWarning: Columns (0,1,2,4,6,8,10,11,12,13,14,15,16,17,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('downloads/enrollee01.txt', sep='\t')

In [11]:
data.head()

,collection_id,enrollee01_id,dataset_id,subjectkey,src_subject_id,interview_date,interview_age,gender,ageyears,ethnicity,...,imagesb,race,chrthlf,version,site,hadintv,visit,collection_title,promoted_subjectkey,study_cohort_name
0,collection_id,enrollee01_id,dataset_id,The NDAR Global Unique Identifier (GUID) for r...,Subject ID how it's defined in lab/project,Date on which the interview/genetic test/sampl...,Age in months at the time of the interview/tes...,Sex of the subject,Age in years,Ethnicity of participant,...,Participant in Image Group B,Race of study subject,"Participant in first half of cohort, or second...",Version/code of assessment,Site,Indicator variable for having had an interim 6...,Visit name,collection_title,promoted_subjectkey,study_cohort_name
1,2343,148676,15628,NDAR_INVE7D0T0U1,9999878,12/01/2005,876,F,NaN,Not Hispanic or Latino,...,0,White,NaN,25,NaN,0,NaN,Osteoarthritis Initiative,NDAR_INVE7D0T0U1,Osteoarthritis Initiative (V02)
2,2343,148675,15628,NDAR_INV4JT0XCK6,9999865,02/17/2006,744,F,NaN,Not Hispanic or Latino,...,0,White,NaN,25,NaN,0,NaN,Osteoarthritis Initiative,NDAR_INV4JT0XCK6,Osteoarthritis Initiative (V02)
3,2343,148671,15628,NDAR_INV1PUE2NE9,9999295,09/20/2005,888,M,NaN,Not Hispanic or Latino,...,0,White,NaN,25,NaN,0,NaN,Osteoarthritis Initiative,NDAR_INV1PUE2NE9,Osteoarthritis Initiative (V02)
4,2343,148668,15628,NDAR_INVK5UEJVXF,9998089,04/25/2006,804,F,NaN,Not Hispanic or Latino,...,0,White,NaN,25,NaN,0,NaN,Osteoarthritis Initiative,NDAR_INVK5UEJVXF,Osteoarthritis Initiative (V02)